_target_: proteingym.models.msa_transformer_model.MSATransformerModel
model_checkpoint: "/home/daniel/proteingym_models/MSA_Transformer/esm_msa1b_t12_100M_UR50S.pt"
sampling_strategy: "sequence-reweighting"
random_seed: 0
nogpu: true
