"""
constant values used throughout package
"""
AA_INTEGER_MAP = {aa: i for i, aa in enumerate("ACDEFGHIKLMNPQRSTVWYXB")}
GAP_CHARACTER = "-"
AA_INTEGER_MAP_ALL = {aa: i for i, aa in enumerate(
    "ACDEFGHIKLMNPQRSTVWYXB"+"ACDEFGHIKLMNPQRSTVWYXB".lower())}
AA_ALPHABET_UPPER = "ACDEFGHIKLMNPQRSTVWYXB"
AA_ALPHABET_ALL = "ACDEFGHIKLMNPQRSTVWYXB" + "ACDEFGHIKLMNPQRSTVWYXB".lower()
