data_folder: "../example_data/mutations"
alignment_folder: "../example_data/msas"
weights_folder: "../example_data/msa_weights"
reference_file: "../example_data/DMS_substitutions.csv"
experiment_index: 20

defaults:
  - model: esm2_8m
  - alignment: default_alignment
  - _self_

